# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_spec/DSSMService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_spec/DSSMService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1eservice_spec/DSSMService.proto\"6\n\x0b\x44SSMRequest\x12\x0b\n\x03qry\x18\x01 \x01(\t\x12\x0c\n\x04\x61ns1\x18\x02 \x01(\t\x12\x0c\n\x04\x61ns2\x18\x03 \x01(\t\"G\n\x0c\x44SSMResponse\x12\x1a\n\x12qry_ans_similarity\x18\x01 \x01(\x02\x12\x1b\n\x13qry_ans2_similarity\x18\x02 \x01(\x02\x32:\n\x04\x44SSM\x12\x32\n\x11semantic_modeling\x12\x0c.DSSMRequest\x1a\r.DSSMResponse\"\x00\x62\x06proto3')
)




_DSSMREQUEST = _descriptor.Descriptor(
  name='DSSMRequest',
  full_name='DSSMRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qry', full_name='DSSMRequest.qry', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ans1', full_name='DSSMRequest.ans1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ans2', full_name='DSSMRequest.ans2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=88,
)


_DSSMRESPONSE = _descriptor.Descriptor(
  name='DSSMResponse',
  full_name='DSSMResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qry_ans_similarity', full_name='DSSMResponse.qry_ans_similarity', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qry_ans2_similarity', full_name='DSSMResponse.qry_ans2_similarity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['DSSMRequest'] = _DSSMREQUEST
DESCRIPTOR.message_types_by_name['DSSMResponse'] = _DSSMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DSSMRequest = _reflection.GeneratedProtocolMessageType('DSSMRequest', (_message.Message,), dict(
  DESCRIPTOR = _DSSMREQUEST,
  __module__ = 'service_spec.DSSMService_pb2'
  # @@protoc_insertion_point(class_scope:DSSMRequest)
  ))
_sym_db.RegisterMessage(DSSMRequest)

DSSMResponse = _reflection.GeneratedProtocolMessageType('DSSMResponse', (_message.Message,), dict(
  DESCRIPTOR = _DSSMRESPONSE,
  __module__ = 'service_spec.DSSMService_pb2'
  # @@protoc_insertion_point(class_scope:DSSMResponse)
  ))
_sym_db.RegisterMessage(DSSMResponse)



_DSSM = _descriptor.ServiceDescriptor(
  name='DSSM',
  full_name='DSSM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=221,
  methods=[
  _descriptor.MethodDescriptor(
    name='semantic_modeling',
    full_name='DSSM.semantic_modeling',
    index=0,
    containing_service=None,
    input_type=_DSSMREQUEST,
    output_type=_DSSMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DSSM)

DESCRIPTOR.services_by_name['DSSM'] = _DSSM

# @@protoc_insertion_point(module_scope)
